# PROJECT_NAME: "VAPT"
TEST:
  # 是否使用wandb,1表示使用,0表示不使用
  WANDB: 0
GPUS_id: 1
FLAG: 1

NUM_GPUS: 1
NUM_SHARDS: 1
RUN_N_TIMES: 1
MODEL:
  INTRO: '131'
  TRANSFER_TYPE: "prompt"
  TYPE: "vit"
  LINEAR:
    MLP_SIZES: [ ]
  PROMPT:
    NUM_TOKENS: 2
    DEEP: True
    DROPOUT: 0.1
    # DROPOUT: 0.5

SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "adamw"
#  OPTIMIZER: "sgd"
  MOMENTUM: 0.9

  WEIGHT_DECAY: 1e-3
  # WEIGHT_DECAY: 1e-4

  LOG_EVERY_N: 100

  # 5% 到 20% 
  # WARMUP_EPOCH: 50
  WARMUP_EPOCH: 10
  TOTAL_EPOCH: 100
  
#  BASE_LR: 1e-3
#  BASE_LR: 0.0006
  BASE_LR: 0.0002
  # BASE_LR: 0.25

DATA:
  NUMBER_CLASSES: 101
  CROPSIZE: 224
  NAME: 'ucf101'
  # 'ucf101' 'k400-tiny'
  BATCH_SIZE: 8
  ROOT_DIR: '/home/yqx/yqx_softlink/data/UCF101/UCF101'
  OUTPUT_DIR: '/home/yqx/yqx_softlink/data/UCF101/UCF101_frames_224'
PROMPT:
  ATTRIBUTE: True
  ATTRIBUTE_DIR: '/home/yqx/yqx_softlink/data/UCF101/224_features_CLIP_cpu'
  ATTRIBUTE_MODE: 'concat-fusion-equal'
#  ATTRIBUTE_MODE: 'all-mask'
#  ATTRIBUTE_MODE: 'all-cap'
#  ATTRIBUTE_MODE: 'all-label'
#  ATTRIBUTE_MODE: '1-4-1-cap'
#  ATTRIBUTE_MODE: '1-4-1-lab'
  ATTRIBUTE_DEPTH_NUM: [11]
#  ATTRIBUTE_DEPTH_NUM: [0]


TRICKS:
  ADAPTER: True
  FLIP: False
  CROP: True